spring:
  application:
    name: auth-service
  profiles:
    include: secret #删掉这行!
    active: ${SPRING_PROFILE_ACTIVE:dev}
  cloud:
    stream:
      bindings:
        register-output:
          destination: register
          content-type: application/json

#写入你的小程序信息
wx:
  miniapp:
    appid:  wx61195d1c5ca45a67
    secret: 4697a9da782ee8b9d84f7177b9f6601a
    msgDataFormat: JSON

jwt:
  pvt-key-file-name: RSA.key
  pub-key-file-name: RSA.pub
  duration: 1D  #JWT 1天过期


